version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

platform: Any CPU

nuget:

  account_feed: true

  project_feed: true

build:

  publish_nuget: true

  publish_nuget_symbols: true

  verbosity: minimal

artifacts:

- path: ./Package

  name: PathButton

deploy:

- provider: GitHub

  auth_token:

    secure: yK4VOGxXgWB8YeFgDqIrkgyxGIeHdX9y7zxzvCoG+0FdYmTE1zq8W+RRfc64RFSA

  draft: false

  force_update: true

  on:

    branch: master

notifications:

- provider: Email

  to:

  - heyixiaoran@vip.qq.com

  on_build_success: false

  on_build_failure: true

  on_build_status_changed: false
